services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futorumeshi-lp-dev
    ports:
      - "3010:3010"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
